with open("input.txt","r") as f:
    file = f.read().strip()
    file = file.split()
    
print("The battle bus has launched!")
print("It is by will alone I set my mind in motion.")
print("It is by the juice of sapho that thoughts acquire speed,")
print("the lips acquire stains.")
print("The stains become a warning.")
print("It is by will alone I set my mind in motion.")
print(f"I'm going to let you in on a secret, {file[0]}.")
print("Things aren't going so well for the Harkonnen.")
print("Are we to sit back and watch as the Emperor gives away Spice that is rightfully ours?")
print("Cheer as the Atreides take our Imperial Basin?")
print("Go. Take some men and mine everything.")